- _pages/unconcious-bias.md
> Fix typo in unconcious-bias.md

- _config.yml
- _pages/interviews/devops.md
- _pages/interviews/engineer.md
- _pages/pre-work/devops.md
Adds additional questions for devops/SRE roles.
To do before merging:
> Devops/sre interview questions.

- _pages/interviews/engineer.md
we're not asking people to design software that an talk through a high level design.
> clarify the elevator question

- _config.yml
- _pages/interviews/consulting-engineer.md
- _pages/interviews/core-values.md
- _pages/resume-review.md
1. Add a consulting engineer section and initial question
2. Add a couple questions that had been suggested and added in the master GDoc
3. Fix some broken links reported in #23
> Hiring site updates

- Dockerfile
- README.md
- docker-compose.yml
Simple Docker harness for running the app locally.
> Dockerize the app for easy local environment

- _pages/interviews.md
Fixes some broken links. This is a follow-on to #34.
> Change `basurl` to `baseurl`

- _pages/interviews/core-values.md
Same question is added to the linked Google Doc.
I can't think of any valid sub-list-items 🤔
> Add new question about prioritizing features

- _pages/pre-work.md
> Homework interviews take an hour

- _pages/pre-work.md
Ask people to include documentation about their development environment.
> Update homework instructions

- _pages/pre-work.md
Already included in the other introductions, we missed this one.
> Include pronouns in introductions for code review interview

- _pages/interviews/checklist.md
Added interviewer checklists for before the interview, right after the interview, and a day after the interview.
> Create interviewer checklist

- _pages/interviews.md
There appeared to be a typo in the interview section with regards to a `you/your` mix-up.
> Fix grammatical error/typo in you/your

- _pages/debrief.md
- _pages/selection.md
@kfoley-18F as previously discussed, I think you’ll probably have some great content to add to these two pages. 
I dumped in a summary, but I’d love to get your eyes and brain cells on improving these two pages specifically — but both of those things are in short supply at the moment, so no worries if this becomes a follow-up task to be done at a later date. 
[Federalist preview link](https://federalist-d68ce676-369e-44d1-a241-edd1b6430adf.app.cloud.gov/preview/18f/eng-hiring/add-debrief-guide/debrief/).
> Add debrief and final selection guides.

- _pages/phone-screens.md
We don’t need to cover GS info in phone screens; it’s already handled by the TTS Talent team. Thanks for the links, @LeighFinkel!
> Link to position information shared from Talent.

- _pages/pre-work.md
@kfoley-18F as discussed — tweaked the language to indicate our current stance on languages.
/cc @LeighFinkel
> Update technical pre-work language.

- Gemfile
- Gemfile.lock
- _data/footer.yml
- _data/navigation.yml
- _includes/notes-reminder.html
- _includes/unconscious-bias-warning.html
- _pages/index.md
- _pages/interviews/technical.md
When served, it raises the exception: "ERROR `/assets/css/main.css' not found." As a result, the page displays only images and links with no styling.
> Upgrade to uswds 2.0

- _guide/_pages/interviews/technical.md
As currently written, the photo app question is getting interpreted as "how would you build instagram?" Adds an example so it's obvious that we're not asking for that. 
Suggested follow-ups (not public):
*How would you approach scaling?*
- Note: For front-end developers, focus on interactions (such as navigating sharing with many users) and robust rendering (such as addressing albums with many images) rather than back-end database and static storage aspects.
*[If the response doesn’t mention users] How would you make sure this solution works for users?*
> Add specificity around the photo app question

- _guide/_pages/interviews/core-values.md
- _guide/_pages/interviews/wrap-up.md
The "what drew you to 18F?" question currently gets asked in 3 different places: the phone screen, the core values, and the wrap-up. It's pretty redundant and doesn't really tend to give super insightful answers, so let's give the core values interview some breathing room.
> Move history and mission question to wrap-up

- _guide/_pages/phone-screens.md
- [?] update values
holding off on updating the intro so that we can have this still geared toward 18f hiring for now
> Update phone screen

- _guide/_pages/interviews/technical.md
update the technical guide to what was in the tts bucket questions 
outstanding: how reference the question links
> update technical questions

- _guide/_pages/index.md
Look over the overview page and include links to the broader interview banking process to close out #129
> Process overview and forking

- .github/workflows/on_add_issue.yml
> Close squiggly bracket for on_add_issue.yml workflow

- .github/workflows/on_add_issue.yml
> Remove permissions scope from GitHub actions token
